server:
  port: 9000

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: identity-service (any)
          uri: http://localhost:8080
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1
        - id: profile-service (any)
          uri: http://localhost:8084
          predicates:
            - Path=/api/profiles/**
          filters:
            - StripPrefix=1