server:
  port: 8888

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: identity-service (any)
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1