spring:
  application:
    name: gglogin
  datasource:
    url: jdbc:mysql://udptbanve.mysql.database.azure.com:3306/udpt_auth_service?useSSL=true&requireSSL=false
    username: banve
    password: udpt123@
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 18665389249-rv54mm7gl1igasegvqfo7um8fmadu442.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
#            scope: openid, profile, email
  data:
    mongodb:
      uri: mongodb://localhost:27017/googleProfile
#            redirect-uri: http://localhost:8088/login/oauth2/code/google
app:
  services:
    profile: http://localhost:8084/profiles
server:
  port: 8088
jwt:
  signerKey: "Svl+niPvuLB7BRr9l1Q54XEsQK+c17DN+cOoEO7du1vAR0fReQjoWwX9Ofe9aEQY"
